eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost

jwt:
  key: AvHGRK8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadweheufHNyG

DB:
  postgres:
    url: jdbc:postgresql://localhost:5432/Users
    username: postgres
    password: LEO
    driver-class-name: org.postgresql.Driver

  mongoDB:
    url: mongodb://localhost:27017/ProductsBase